# Generated by Django 5.2.8 on 2025-12-03 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='알러지 항원명')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('food_class', models.CharField(blank=True, max_length=100)),
                ('energy_kcal', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('fat_g', models.FloatField(blank=True, null=True)),
                ('carbohydrate_g', models.FloatField(blank=True, null=True)),
                ('sugars_g', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('main_ingredients', models.JSONField(default=list, verbose_name='주요_재료')),
                ('taste_profile', models.JSONField(default=list, verbose_name='맛_특징')),
                ('cooking_method', models.CharField(blank=True, max_length=100, verbose_name='조리_방식')),
                ('situational_tags', models.JSONField(default=list, verbose_name='상황_태그')),
                ('allergens', models.ManyToManyField(blank=True, related_name='foods_containing', to='food_app.allergen', verbose_name='포함된 알러지 항원')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_g', models.FloatField(verbose_name='섭취량(g)')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food_app.food', verbose_name='음식')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food_app.meal')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('activity_level', models.CharField(blank=True, choices=[('low', '활동 적음'), ('light', '약간 활동적'), ('active', '활동적'), ('very_active', '매우 활동적')], max_length=20)),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='채식주의자')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='비건')),
                ('allergies', models.ManyToManyField(blank=True, related_name='users_with_allergy', to='food_app.allergen', verbose_name='알러지 정보')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('LIKE', '좋아요'), ('DISLIKE', '싫어요')], max_length=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='food_app.food')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to='food_app.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'food')},
            },
        ),
    ]
