# Generated by Django 5.2.8 on 2025-12-03 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_meal_mealitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='알러지 항원명')),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='total_kcal',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='food_name',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='nutrition',
        ),
        migrations.RemoveField(
            model_name='mealitem',
            name='pred_class',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='비건'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='채식주의자'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='weight_g',
            field=models.FloatField(verbose_name='섭취량(g)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='users_with_allergy', to='food_app.allergen', verbose_name='알러지 정보'),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('food_class', models.CharField(blank=True, max_length=100)),
                ('energy_kcal', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('fat_g', models.FloatField(blank=True, null=True)),
                ('carbohydrate_g', models.FloatField(blank=True, null=True)),
                ('sugars_g', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('main_ingredients', models.JSONField(default=list, verbose_name='주요_재료')),
                ('taste_profile', models.JSONField(default=list, verbose_name='맛_특징')),
                ('cooking_method', models.CharField(blank=True, max_length=100, verbose_name='조리_방식')),
                ('situational_tags', models.JSONField(default=list, verbose_name='상황_태그')),
                ('allergens', models.ManyToManyField(blank=True, related_name='foods_containing', to='food_app.allergen', verbose_name='포함된 알러지 항원')),
            ],
        ),
        migrations.AddField(
            model_name='mealitem',
            name='food',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='food_app.food', verbose_name='음식'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserFoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(choices=[('LIKE', '좋아요'), ('DISLIKE', '싫어요')], max_length=10)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='food_app.food')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to='food_app.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'food')},
            },
        ),
    ]
